-- for postgresql

CREATE SCHEMA IF NOT EXISTS daga_test;

CREATE TABLE IF NOT EXISTS daga_test.tbl_user
(
 id SERIAL PRIMARY KEY NOT NULL,
 name CHAR(100) NOT NULL,
 lastName CHAR(100) NOT NULL,
 email CHAR(100) NOT NULL,
 photoUrl CHAR(300) NULL,
 isValid BOOLEAN NOT NULL DEFAULT TRUE,
 createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
 updatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
 deletedAt TIMESTAMP NULL
);
